modLoader="javafml"
loaderVersion="[33,)"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/CoffeeCatRailway/TheDeadlands/issues"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${name}"
logoFile="logo.png"
credits=""
authors="${author}"
description='''

'''

[[dependencies.coffeecheese]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="BOTH"
[[dependencies.coffeecheese]]
modId="minecraft"
mandatory=true
versionRange="[${mcVersion}]"
ordering="NONE"
side="BOTH"
[[dependencies.coffeecheese]]
modId="jei"
mandatory=false
versionRange="[7,]"
ordering="NONE"
side="CLIENT"